import React, { useCallback, useState } from "react";
import {
  Platform,
  View,
  Text,
  TouchableOpacity,
  Image,
  StyleSheet,
  ActivityIndicator,
} from "react-native";
import { useTheme } from "./ThemeProvider";
import { uploadTradeImage, uploadNoteImage } from "../services/supabaseImageService";

type LabeledScreenshot = { uri: string; label?: string };

type ImageUploaderProps = {
  screenshots: LabeledScreenshot[];
  onAdd: (localUri: string, file?: File) => void;
  onRemove: (uri: string) => void;
  onUpdateLabel?: (uri: string, label: string) => void;
  maxImages?: number;
  thumbnailSize?: number;
  thumbnailMargin?: number;
  bucketType?: 'trade' | 'note'; // Added option to specify which bucket to use
};

export default function ImageUploader({
  screenshots,
  onAdd,
  onRemove,
  onUpdateLabel,
  maxImages = 5,
  thumbnailSize = 100,
  thumbnailMargin = 12,
  bucketType = 'trade', // Default to trade bucket for backward compatibility
}: ImageUploaderProps) {
  const { colors } = useTheme();
  const [uploading, setUploading] = useState(false);
  const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);

  const handleWebPicker = useCallback(() => {
    const input = document.createElement("input");
    input.type = "file";
    input.accept = "image/*";
    input.multiple = false;
    
    input.onchange = async (e: any) => {
      const file: File = e.target.files?.[0];
      if (!file) return;
      
      setUploading(true);
      try {
        // Generate a temporary ID for the trade/page (in a real app, this would come from context or be generated by backend)
        const tempId = `temp_${Date.now()}`;
        let supabaseUrl: string | null;
        
        if (bucketType === 'note') {
          // For note images, use the n-images bucket
          supabaseUrl = await uploadNoteImage(tempId, file);
        } else {
          // For trade images, use the default trade-images bucket
          supabaseUrl = await uploadTradeImage(tempId, file);
        }
        
        if (supabaseUrl) {
          onAdd(supabaseUrl);
        } else {
          // fallback to local preview if upload fails
          const url = URL.createObjectURL(file);
          onAdd(url);
        }
      } catch (error) {
        console.error("Upload error:", error);
        // Even if upload fails, we still want to show the image locally
        const url = URL.createObjectURL(file);
        onAdd(url);
      } finally {
        setUploading(false);
      }
    };
    
    input.click();
  }, [onAdd, bucketType]);

  const handleNative = useCallback(async () => {
    try {
      if (Platform.OS === "web") {
        console.warn(
          "Image picker not available on web, use handleWebPicker instead"
        );
        return;
      }

      setUploading(true);
      const ImagePicker = await import("expo-image-picker");
      const res = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        quality: 0.8,
        allowsEditing: true,
        aspect: [16, 9],
      });
      
      if (!res.canceled && "uri" in res && typeof res.uri === "string") {
        onAdd(res.uri);
      }
    } catch (err) {
      console.error("Image picker error (this is normal on web):", err);
      if (Platform.OS === "web") {
        console.info("Falling back to web file picker...");
        handleWebPicker();
      }
    } finally {
      setUploading(false);
    }
  }, [onAdd, handleWebPicker]);

  const handlePress = useCallback(() => {
    if (screenshots.length >= maxImages) {
      return; // Max images reached
    }
    
    if (Platform.OS === "web") {
      handleWebPicker();
    } else {
      handleNative();
    }
  }, [handleWebPicker, handleNative, screenshots.length, maxImages]);

  const canAddMore = screenshots.length < maxImages;

  return (
    <View style={styles.container}>
      {/* Header */}
      {screenshots.length > 0 && (
        <View style={styles.header}>
          <Text style={[styles.headerText, { color: colors.text }]}>
            Screenshots
          </Text>
          <Text style={[styles.countText, { color: colors.subtext }]}>
            {screenshots.length} / {maxImages}
          </Text>
        </View>
      )}

      {/* Image Grid */}
      {screenshots.length > 0 && (
        <View style={styles.grid}>
          {screenshots.map((s, index) => (
            <View
              key={s.uri}
              style={[
                styles.imageWrapper,
                {
                  borderColor: hoveredIndex === index ? colors.highlight : 'transparent',
                  borderWidth: 2,
                  marginRight: thumbnailMargin || 12,
                  marginBottom: thumbnailMargin || 12,
                },
              ]}
              {...Platform.select({
                web: {
                  onMouseEnter: () => setHoveredIndex(index),
                  onMouseLeave: () => setHoveredIndex(null),
                },
                default: {},
              })}
            >
              <Image
                source={{ uri: s.uri }}
                style={[styles.thumbnail, { width: thumbnailSize, height: thumbnailSize, borderRadius: Math.max(8, Math.floor(thumbnailSize * 0.1)), backgroundColor: colors.surface }]}
                resizeMode="cover"
              />

              {/* Overlay on hover/press */}
              {hoveredIndex === index && (
                <View style={[styles.overlay, { backgroundColor: 'rgba(0,0,0,0.6)' }]}>
                  <Text style={[styles.overlayText, { color: colors.text }]}>
                    #{index + 1}
                  </Text>
                </View>
              )}

              {/* Label chip */}
              <TouchableOpacity
                style={[styles.labelChip, { backgroundColor: 'rgba(0,0,0,0.5)' }]}
                onPress={() => {
                  const nextLabels = ['Entry','Exit','Pattern','News','Other'];
                  const current = s.label || 'Other';
                  const next = nextLabels[(nextLabels.indexOf(current) + 1) % nextLabels.length] || 'Other';
                  onUpdateLabel && onUpdateLabel(s.uri, next);
                }}
              >
                <Text style={[styles.labelText, { color: colors.text }]}>{s.label || 'Other'}</Text>
              </TouchableOpacity>

              {/* Remove button */}
              <TouchableOpacity
                style={[
                  styles.removeButton,
                  {
                    backgroundColor: colors.lossEnd,
                    shadowColor: colors.lossEnd,
                  },
                ]}
                onPress={() => onRemove(s.uri)}
                accessibilityLabel="Remove image"
                activeOpacity={0.8}
              >
                <Text style={[styles.removeIcon, { color: '#fff' }]}>×</Text>
              </TouchableOpacity>
            </View>
          ))}
        </View>
      )}

      {/* Upload Button */}
      {canAddMore && (
        <TouchableOpacity
          style={[
            styles.uploadButton,
            {
              backgroundColor: uploading ? colors.neutral : `${colors.highlight}20`,
              borderColor: colors.highlight,
              borderWidth: 2,
              borderStyle: 'dashed',
            },
          ]}
          onPress={handlePress}
          accessibilityLabel="Upload screenshot"
          disabled={uploading}
          activeOpacity={0.7}
        >
          {uploading ? (
            <View style={styles.uploadingContainer}>
              <ActivityIndicator size="small" color={colors.highlight} />
              <Text style={[styles.uploadingText, { color: colors.subtext }]}>
                Uploading...
              </Text>
            </View>
          ) : (
            <View style={styles.uploadContent}>
              <Text style={[styles.uploadIcon, { color: colors.highlight }]}>
                📸
              </Text>
              <Text style={[styles.uploadText, { color: colors.text }]}>
                {screenshots.length === 0
                  ? Platform.OS === "web"
                    ? "Choose Images"
                    : "Add Screenshots"
                  : "Add More"}
              </Text>
              <Text style={[styles.uploadHint, { color: colors.subtext }]}>
                {Platform.OS === "web" 
                  ? "Click to browse"
                  : "Tap to select from gallery"}
              </Text>
            </View>
          )}
        </TouchableOpacity>
      )}

      {/* Max reached message */}
      {!canAddMore && (
        <View style={[styles.maxReachedContainer, { backgroundColor: `${colors.neutral}80` }]}>
          <Text style={[styles.maxReachedText, { color: colors.subtext }]}>
            Maximum {maxImages} images reached
          </Text>
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    gap: 12,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  headerText: {
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  countText: {
    fontSize: 12,
    fontWeight: "600",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  imageWrapper: {
    position: "relative",
    borderRadius: 12,
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  thumbnail: {
    width: 100,
    height: 100,
    borderRadius: 10,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  overlayText: {
    fontSize: 16,
    fontWeight: "700",
  },
  removeButton: {
    position: "absolute",
    top: -6,
    right: -6,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  removeIcon: {
    fontWeight: "700",
    fontSize: 20,
    lineHeight: 22,
  },
  uploadButton: {
    paddingVertical: 32,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 120,
  },
  labelChip: {
    position: 'absolute',
    left: 8,
    bottom: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  labelText: {
    fontSize: 11,
    fontWeight: '700',
  },
  uploadingContainer: {
    alignItems: "center",
    gap: 12,
  },
  uploadingText: {
    fontSize: 13,
    fontWeight: "600",
  },
  uploadContent: {
    alignItems: "center",
    gap: 8,
  },
  uploadIcon: {
    fontSize: 40,
    marginBottom: 4,
  },
  uploadText: {
    fontWeight: "700",
    fontSize: 15,
    letterSpacing: 0.3,
  },
  uploadHint: {
    fontSize: 12,
    fontWeight: "500",
  },
  maxReachedContainer: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
  },
  maxReachedText: {
    fontSize: 12,
    fontWeight: "600",
  },
});